version: '3.9'

services:  
  app:
    build: 
      context: ./
      target: dev
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    ports:
      - 8080:8080
    depends_on:
      - courses-db
    volumes:
      - ./:/var/www/html

  courses-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: movies
      POSTGRES_PASSWORD: movies_secret
      POSTGRES_DB: movies
    volumes:
      - courses-db:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    ports:
      - 6380:6379
    volumes:
      - redis:/data

  meilisearch:
    image: getmeili/meilisearch:v1.20
    ports:
      - 7700:7700
    environment:
      MEILI_NO_ANALYTICS: 'true'
      MEILI_ENV: 'development'
      MEILI_MASTER_KEY: 'masterKey'
    volumes:
      - meilisearch:/meili_data/data.ms

volumes:
  courses-db:
  redis:
  meilisearch: